services:
  db:
    container_name: postgres_container
    image: postgres:17.10
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    networks:
      - my_network

  af:
    container_name: airflow_container
    image: apache/airflow:3.3.0
    env_file:
      - ${ENV_FILE_PATH:-.env.docker}
    ports:
      - 8080:8080
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/config:/opt/airflow/config
      - ./airflow/plugins:/opt/airflow/plugins
      - ./app:/opt/airflow/app
      - ./data:/opt/airflow/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    networks:
      - my_network
    command: >
      bash -c "airflow db migrate && airflow standalone"

  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres
    platform: linux/amd64
    volumes:
      - ./dbt/fragtracker:/usr/app
      - ./dbt/fragtracker:/root/.dbt
    depends_on:
      - db
    networks:
      - my_network
    command: run

networks:
  my_network:
    driver: bridge