services:
  db:
    container_name: postgres_container
    image: postgres:17.10
    ports:
      - "${HOST_IP:-127.0.0.1}:5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    networks:
      - my_network
    restart: unless-stopped

  af:
    container_name: airflow_container
    image: apache/airflow:3.3.0
    group_add:
    - ${DOCKER_GID:-0}
    env_file:
      - ${ENV_FILE_PATH:-.env}
    ports:
      - "${HOST_IP:-127.0.0.1}:8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/config:/opt/airflow/config
      - ./airflow/plugins:/opt/airflow/plugins
      - ./app:/opt/airflow/app
      - ./data:/opt/airflow/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONPATH=/opt/airflow:/opt/airflow/app
      - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS=admin:admin
      - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE=/opt/airflow/config/passwords.json
      - AIRFLOW__CORE__FERNET_KEY:${AIRFLOW__CORE__FERNET_KEY}
    depends_on:
      - db
    networks:
      - my_network
    command: >
      bash -c "airflow db migrate && airflow standalone"
    restart: unless-stopped

  dbt:
    container_name: dbt_container
    build:
      dockerfile: Dockerfile
    image: frag-track-dbt:latest
    command: ["true"]
    
  python:
    container_name: python_container
    build:
      dockerfile: Dockerfile
    env_file:
      - ${ENV_FILE_PATH:-.env}
    volumes:
      - ./app:/app
      - ./data:/data
      - /app/.venv
    environment:
      - PATH=/app/.venv/bin:$PATH
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - my_network
    command: uv run gunicorn -w 2 -b 0.0.0.0:5001 main:app
    restart: unless-stopped

  cloudflared:
    container_name: cloudflared_container
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    driver: bridge